# Generated by Django 4.0.4 on 2022-05-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchagency',
            old_name='name',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='researchdepartment',
            old_name='name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='researchmodel',
            old_name='name',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='researchscope',
            old_name='name',
            new_name='scope',
        ),
        migrations.RenameField(
            model_name='researchtype',
            old_name='name',
            new_name='type',
        ),
    ]
