# Generated by Django 4.0.4 on 2022-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_rename_name_researchagency_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='id',
        ),
        migrations.AlterField(
            model_name='research',
            name='task_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='과제번호'),
        ),
    ]
