# Generated by Django 4.0.4 on 2022-05-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_remove_research_id_alter_research_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='research',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='researchagency',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='researchagency',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='researchdepartment',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='researchdepartment',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='researchmodel',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='researchmodel',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='researchscope',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='researchscope',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='researchtype',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='researchtype',
            name='is_delete',
        ),
    ]
